-- Global Student Sheets Migration
-- Creates all tables needed for global student sheets system

CREATE TABLE IF NOT EXISTS global_student_sheets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id VARCHAR(50) UNIQUE,
  student_code VARCHAR(50),
  username VARCHAR(100),
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  email VARCHAR(200),
  phone VARCHAR(50),
  gender ENUM('male', 'female', 'other'),
  date_of_birth DATE,
  trade_code VARCHAR(50),
  trade_name VARCHAR(200),
  level_number INT,
  level_suffix VARCHAR(10),
  class_name VARCHAR(200),
  academic_year VARCHAR(20),
  status ENUM('active', 'inactive', 'suspended', 'graduated', 'transferred') DEFAULT 'active',
  total_subjects INT DEFAULT 0,
  total_marks DECIMAL(10,2) DEFAULT 0,
  average_marks DECIMAL(10,2) DEFAULT 0,
  overall_grade VARCHAR(5),
  gpa DECIMAL(4,2) DEFAULT 0,
  total_days INT DEFAULT 0,
  days_present INT DEFAULT 0,
  days_absent INT DEFAULT 0,
  days_late INT DEFAULT 0,
  attendance_percentage DECIMAL(10,2) DEFAULT 100,
  total_incidents INT DEFAULT 0,
  critical_incidents INT DEFAULT 0,
  high_incidents INT DEFAULT 0,
  medium_incidents INT DEFAULT 0,
  low_incidents INT DEFAULT 0,
  conduct_score INT DEFAULT 100,
  conduct_grade VARCHAR(5) DEFAULT 'A',
  total_fees DECIMAL(10,2) DEFAULT 0,
  paid_amount DECIMAL(10,2) DEFAULT 0,
  balance DECIMAL(10,2) DEFAULT 0,
  payment_status ENUM('unpaid', 'partial', 'paid') DEFAULT 'unpaid',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_student_id (student_id),
  INDEX idx_trade (trade_code),
  INDEX idx_level (level_number),
  INDEX idx_status (status)
);

CREATE TABLE IF NOT EXISTS student_attendance_records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sheet_id INT,
  student_id VARCHAR(50),
  attendance_date DATE,
  status ENUM('present', 'absent', 'late', 'excused', 'sick', 'leave'),
  subject VARCHAR(200),
  period VARCHAR(50),
  marked_by VARCHAR(50),
  marked_by_name VARCHAR(200),
  marked_by_role VARCHAR(50),
  remarks TEXT,
  marked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_attendance (student_id, attendance_date, subject, period),
  INDEX idx_student_date (student_id, attendance_date)
);

CREATE TABLE IF NOT EXISTS student_subject_performance (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sheet_id INT,
  student_id VARCHAR(50),
  subject_code VARCHAR(50),
  subject_name VARCHAR(200),
  term VARCHAR(50),
  academic_year VARCHAR(20),
  quiz_marks DECIMAL(10,2) DEFAULT 0,
  midterm_marks DECIMAL(10,2) DEFAULT 0,
  final_marks DECIMAL(10,2) DEFAULT 0,
  total_marks DECIMAL(10,2) DEFAULT 0,
  percentage DECIMAL(10,2) DEFAULT 0,
  grade VARCHAR(5),
  grade_points DECIMAL(4,2) DEFAULT 0,
  teacher_id VARCHAR(50),
  teacher_name VARCHAR(200),
  remarks TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_performance (student_id, subject_code, term, academic_year),
  INDEX idx_student_term (student_id, term, academic_year)
);

CREATE TABLE IF NOT EXISTS student_discipline_records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sheet_id INT,
  student_id VARCHAR(50),
  incident_date DATE,
  incident_type VARCHAR(100),
  severity ENUM('low', 'medium', 'high', 'critical'),
  category VARCHAR(100),
  description TEXT,
  location VARCHAR(200),
  witnesses TEXT,
  action_taken TEXT,
  punishment TEXT,
  punishment_start DATE,
  punishment_end DATE,
  status ENUM('active', 'resolved', 'appealed') DEFAULT 'active',
  recorded_by VARCHAR(50),
  recorded_by_name VARCHAR(200),
  recorded_by_role VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_student (student_id),
  INDEX idx_severity (severity)
);

CREATE TABLE IF NOT EXISTS student_payment_records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sheet_id INT,
  student_id VARCHAR(50),
  payment_date DATE,
  payment_type VARCHAR(100),
  amount DECIMAL(10,2),
  payment_method ENUM('cash', 'bank', 'mobile', 'cheque', 'other'),
  receipt_number VARCHAR(100),
  reference_number VARCHAR(100),
  term VARCHAR(50),
  academic_year VARCHAR(20),
  description TEXT,
  notes TEXT,
  status ENUM('pending', 'confirmed', 'rejected', 'refunded') DEFAULT 'pending',
  recorded_by VARCHAR(50),
  recorded_by_name VARCHAR(200),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_student (student_id),
  INDEX idx_status (status)
);

CREATE TABLE IF NOT EXISTS student_conduct_tracking (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sheet_id INT,
  student_id VARCHAR(50),
  total_incidents INT DEFAULT 0,
  critical_incidents INT DEFAULT 0,
  high_incidents INT DEFAULT 0,
  medium_incidents INT DEFAULT 0,
  low_incidents INT DEFAULT 0,
  deductions INT DEFAULT 0,
  final_score INT DEFAULT 100,
  conduct_grade VARCHAR(5) DEFAULT 'A',
  conduct_status ENUM('excellent', 'good', 'fair', 'poor') DEFAULT 'good',
  last_incident_date DATE,
  last_incident_type VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_student (student_id)
);

CREATE TABLE IF NOT EXISTS student_attendance_summary (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sheet_id INT,
  student_id VARCHAR(50),
  month VARCHAR(50),
  year INT,
  total_days INT DEFAULT 0,
  present_days INT DEFAULT 0,
  absent_days INT DEFAULT 0,
  late_days INT DEFAULT 0,
  excused_days INT DEFAULT 0,
  sick_days INT DEFAULT 0,
  attendance_rate DECIMAL(10,2) DEFAULT 100,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_summary (student_id, month, year)
);

CREATE TABLE IF NOT EXISTS student_term_reports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sheet_id INT,
  student_id VARCHAR(50),
  term VARCHAR(50),
  academic_year VARCHAR(20),
  total_subjects INT DEFAULT 0,
  total_marks DECIMAL(10,2) DEFAULT 0,
  average_marks DECIMAL(10,2) DEFAULT 0,
  gpa DECIMAL(4,2) DEFAULT 0,
  overall_grade VARCHAR(5),
  attendance_rate DECIMAL(10,2) DEFAULT 100,
  days_present INT DEFAULT 0,
  days_absent INT DEFAULT 0,
  days_late INT DEFAULT 0,
  conduct_score INT DEFAULT 100,
  conduct_grade VARCHAR(5) DEFAULT 'A',
  total_incidents INT DEFAULT 0,
  class_teacher_comment TEXT,
  dos_comment TEXT,
  principal_comment TEXT,
  status ENUM('draft', 'published', 'archived') DEFAULT 'draft',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_report (student_id, term, academic_year)
);

CREATE TABLE IF NOT EXISTS student_sheet_custom_columns (
  id INT AUTO_INCREMENT PRIMARY KEY,
  column_name VARCHAR(100),
  column_label VARCHAR(200),
  column_type ENUM('text', 'number', 'date', 'boolean', 'select', 'textarea', 'file'),
  select_options TEXT,
  calculation_formula TEXT,
  created_by_role VARCHAR(50),
  visible_to_roles TEXT,
  editable_by_roles TEXT,
  scope ENUM('global', 'trade', 'level', 'class') DEFAULT 'global',
  scope_value VARCHAR(100),
  display_order INT DEFAULT 0,
  is_required TINYINT(1) DEFAULT 0,
  is_active TINYINT(1) DEFAULT 1,
  created_by VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student_sheet_custom_values (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sheet_id INT,
  student_id VARCHAR(50),
  column_id INT,
  value_text TEXT,
  value_number DECIMAL(15,4),
  value_date DATE,
  value_boolean TINYINT(1) DEFAULT 0,
  updated_by VARCHAR(50),
  updated_by_role VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_value (student_id, column_id)
);
