-- Payment Proof Submissions Table
CREATE TABLE IF NOT EXISTS payment_proofs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  submission_number VARCHAR(100) UNIQUE NOT NULL,
  parent_id INT NOT NULL,
  student_id INT NOT NULL,
  student_name VARCHAR(255),
  student_code VARCHAR(50),
  trade VARCHAR(50),
  level VARCHAR(20),
  amount_paid DECIMAL(10, 2) NOT NULL,
  payment_date DATE NOT NULL,
  payment_method VARCHAR(50),
  reference_number VARCHAR(100),
  bank_name VARCHAR(100),
  transaction_id VARCHAR(100),
  proof_image VARCHAR(500),
  notes TEXT,
  status ENUM('pending', 'verified', 'rejected', 'processed') DEFAULT 'pending',
  verified_by INT,
  verified_at DATETIME,
  verification_notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (parent_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_parent_id (parent_id),
  INDEX idx_student_id (student_id),
  INDEX idx_status (status),
  INDEX idx_payment_date (payment_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
