import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'fr' | 'rw' | 'sw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Extended translations with comprehensive Kinyarwanda support
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    home: 'HOME',
    sports: 'SPORTS',
    services: 'SERVICES',
    trades: 'TRADES',
    contactUs: 'CONTACT US',
    supports: 'SUPPORTS',
    login: 'LOGIN',
    register: 'REGISTER',
    // Hero
    heroTitle: 'EMPOWERING FUTURE SKILLS',
    heroSubtitle: 'Building Tomorrow\'s Professionals Today',
    // Trades
    tradesOffered: 'TRADES OFFERED',
    softwareDevelopment: 'Software Development',
    buildingConstruction: 'Building Construction',
    automobileTechnology: 'Automobile Technology',
    sod: 'SOD',
    bdc: 'BDC',
    // Portal
    upcomingEvents: 'UPCOMING EVENTS',
    studentParentPortal: 'STUDENT & PARENT PORTAL',
    studentPortal: 'Student Portal',
    studentAndParent: 'Student & Parent',
    // Footer
    quickLinks: 'QUICK LINKS',
    contactInfo: 'CONTACT INFO',
    newsletter: 'NEWSLETTER',
    // Forms
    email: 'Email address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    enterStaffCode: 'ENTER STAFF CODE',
    cancel: 'CANCEL',
    submit: 'Submit',
    // Search
    searchPlaceholder: 'Search everything...',
    // More
    learnMore: 'Learn More',
    viewAll: 'View All',
    getStarted: 'Get Started',
    // Dashboard terms
    dashboard: 'Dashboard',
    overview: 'Overview',
    analytics: 'Analytics',
    reports: 'Reports',
    settings: 'Settings',
    profile: 'Profile',
    notifications: 'Notifications',
    logout: 'Logout',
    // Academic terms
    courses: 'Courses',
    grades: 'Grades',
    attendance: 'Attendance',
    assignments: 'Assignments',
    exams: 'Exams',
    schedule: 'Schedule',
    // Advanced features
    artificialIntelligence: 'Artificial Intelligence',
    blockchain: 'Blockchain',
    iot: 'Internet of Things',
    biometric: 'Biometric',
    augmentedReality: 'Augmented Reality',
    predictiveAnalytics: 'Predictive Analytics',
    smartEnergy: 'Smart Energy',
    quantumSecurity: 'Quantum Security',
    // System messages
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Information',
    // Support page
    supportCenter: 'Support Center',
    howCanWeHelp: 'How Can We Help You?',
    supportDescription: 'Find answers, watch tutorials, submit tickets, and get the support you need.',
    searchHelpArticles: 'Search for help articles, tutorials, or common issues...',
    knowledgeBase: 'Knowledge Base',
    videoTutorials: 'Video Tutorials',
    supportTickets: 'Support Tickets',
    contactSupport: 'Contact Support',
    submitTicket: 'Submit Ticket',
    browseArticles: 'Browse help articles',
    watchGuides: 'Watch step-by-step guides',
    getPersonalizedHelp: 'Get personalized help',
    speakWithTeam: 'Speak with our team',
    activeUsers: 'Active Users',
    resolvedTickets: 'Resolved Tickets',
    avgResponseTime: 'Avg Response Time',
    satisfactionRate: 'Satisfaction Rate',
    fastResponse: 'Fast Response',
    available247: '24/7 Available',
    articles: 'Articles',
    videos: 'Videos',
    // Academic page
    academics: 'Academics',
    academicsDescription: 'Courses, Exams & Results',
    allCourses: 'All Courses',
    upcomingExams: 'Upcoming Exams',
    myResults: 'My Results',
    courseProgress: 'Course Progress',
    students: 'Students',
    instructor: 'Instructor',
    duration: 'Duration',
    materials: 'Materials',
    viewMore: 'View More',
    examDate: 'Exam Date',
    examTime: 'Exam Time',
    examRoom: 'Exam Room',
    score: 'Score',
    percentage: 'Percentage',
    rank: 'Rank',
    downloadResult: 'Download Result',
  },
  fr: {
    home: 'ACCUEIL',
    sports: 'SPORTS',
    services: 'SERVICES',
    trades: 'MÉTIERS',
    contactUs: 'CONTACTEZ-NOUS',
    supports: 'SUPPORTS',
    login: 'CONNEXION',
    register: 'S\'INSCRIRE',
    heroTitle: 'DÉVELOPPEMENT LOGICIEL',
    heroSubtitle: 'Former les Professionnels de Demain Aujourd\'hui',
    tradesOffered: 'MÉTIERS OFFERTS',
    softwareDevelopment: 'Développement Logiciel',
    buildingConstruction: 'Construction de Bâtiments',
    automobileTechnology: 'Technologie Automobile',
    sod: 'SOD',
    bdc: 'BDC',
    upcomingEvents: 'ÉVÉNEMENTS À VENIR',
    studentParentPortal: 'PORTAIL ÉTUDIANTS ET PARENTS',
    studentPortal: 'Portail Étudiant',
    studentAndParent: 'Étudiant et Parent',
    quickLinks: 'LIENS RAPIDES',
    contactInfo: 'INFORMATIONS DE CONTACT',
    newsletter: 'NEWSLETTER',
    email: 'Adresse e-mail',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    fullName: 'Nom complet',
    phoneNumber: 'Numéro de téléphone',
    signIn: 'Se connecter',
    signUp: 'S\'inscrire',
    enterStaffCode: 'ENTRER LE CODE DU PERSONNEL',
    cancel: 'ANNULER',
    submit: 'Soumettre',
    searchPlaceholder: 'Rechercher tout...',
    learnMore: 'En savoir plus',
    viewAll: 'Voir tout',
    getStarted: 'Commencer',
    // Dashboard terms
    dashboard: 'Tableau de bord',
    overview: 'Vue d\'ensemble',
    analytics: 'Analytiques',
    reports: 'Rapports',
    settings: 'Paramètres',
    profile: 'Profil',
    notifications: 'Notifications',
    logout: 'Déconnexion',
    // Academic terms
    courses: 'Cours',
    grades: 'Notes',
    attendance: 'Présence',
    assignments: 'Devoirs',
    exams: 'Examens',
    schedule: 'Horaire',
    // Advanced features
    artificialIntelligence: 'Intelligence Artificielle',
    blockchain: 'Blockchain',
    iot: 'Internet des Objets',
    biometric: 'Biométrique',
    augmentedReality: 'Réalité Augmentée',
    predictiveAnalytics: 'Analytiques Prédictives',
    smartEnergy: 'Énergie Intelligente',
    quantumSecurity: 'Sécurité Quantique',
    // System messages
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    warning: 'Attention',
    info: 'Information',
    // Support page
    supportCenter: 'Centre d\'Assistance',
    howCanWeHelp: 'Comment Pouvons-Nous Vous Aider?',
    supportDescription: 'Trouvez des réponses, regardez des tutoriels, soumettez des tickets et obtenez l\'aide dont vous avez besoin.',
    searchHelpArticles: 'Rechercher des articles d\'aide, des tutoriels ou des problèmes courants...',
    knowledgeBase: 'Base de Connaissances',
    videoTutorials: 'Tutoriels Vidéo',
    supportTickets: 'Tickets de Support',
    contactSupport: 'Contacter le Support',
    submitTicket: 'Soumettre un Ticket',
    browseArticles: 'Parcourir les articles d\'aide',
    watchGuides: 'Regarder les guides étape par étape',
    getPersonalizedHelp: 'Obtenir une aide personnalisée',
    speakWithTeam: 'Parler avec notre équipe',
    activeUsers: 'Utilisateurs Actifs',
    resolvedTickets: 'Tickets Résolus',
    avgResponseTime: 'Temps de Réponse Moyen',
    satisfactionRate: 'Taux de Satisfaction',
    fastResponse: 'Réponse Rapide',
    available247: 'Disponible 24/7',
    articles: 'Articles',
    videos: 'Vidéos',
    // Academic page
    academics: 'Académiques',
    academicsDescription: 'Cours, Examens et Résultats',
    allCourses: 'Tous les Cours',
    upcomingExams: 'Examens à Venir',
    myResults: 'Mes Résultats',
    courseProgress: 'Progrès du Cours',
    students: 'Étudiants',
    instructor: 'Instructeur',
    duration: 'Durée',
    materials: 'Matériaux',
    viewMore: 'Voir Plus',
    examDate: 'Date d\'Examen',
    examTime: 'Heure d\'Examen',
    examRoom: 'Salle d\'Examen',
    score: 'Score',
    percentage: 'Pourcentage',
    rank: 'Rang',
    downloadResult: 'Télécharger le Résultat',
  },
  rw: {
    home: 'AHABANZA',
    sports: 'SIPORO',
    services: 'SERIVISI',
    trades: 'AMAHUGURWA',
    contactUs: 'TWANDIKIRE',
    supports: 'UBUFASHA',
    login: 'KWINJIRA',
    register: 'IYANDIKISHE',
    heroTitle: 'GUTEZA IMBERE UBUMENYI',
    heroSubtitle: 'Twubaka Abahanga b\'Ejo Uyu Munsi',
    tradesOffered: 'AMAHUGURWA ATANGWA',
    softwareDevelopment: 'Iterambere rya Porogaramu',
    buildingConstruction: 'Ubwubatsi',
    automobileTechnology: 'Ikoranabuhanga ry\'Imodoka',
    sod: 'SOD',
    bdc: 'BDC',
    upcomingEvents: 'IBIRORI BIZAZA',
    studentParentPortal: 'URUBUGA RW\'ABANYESHURI N\'ABABYEYI',
    studentPortal: 'Urubuga rw\'Abanyeshuri',
    studentAndParent: 'Umunyeshuri & Umubyeyi',
    quickLinks: 'AMAHUZA YIHUSE',
    contactInfo: 'AMAKURU Y\'ITUMANAHO',
    newsletter: 'INKURU',
    email: 'Aderesi ya imeyili',
    password: 'Ijambo ry\'ibanga',
    confirmPassword: 'Emeza ijambo ry\'ibanga',
    fullName: 'Amazina yose',
    phoneNumber: 'Nimero ya terefone',
    signIn: 'Injira',
    signUp: 'Iyandikishe',
    enterStaffCode: 'INJIZA KODE Y\'ABAKOZI',
    cancel: 'HAGARIKA',
    submit: 'Ohereza',
    searchPlaceholder: 'Shakisha byose...',
    learnMore: 'Menya byinshi',
    viewAll: 'Reba byose',
    getStarted: 'Tangira',
    // Dashboard terms
    dashboard: 'Ikimenyetso',
    overview: 'Icyerekezo rusange',
    analytics: 'Isesengura',
    reports: 'Raporo',
    settings: 'Igenamigambi',
    profile: 'Umwirondoro',
    notifications: 'Ubutumwa',
    logout: 'Gusohoka',
    // Academic terms
    courses: 'Amasomo',
    grades: 'Amanota',
    attendance: 'Kwitabira',
    assignments: 'Akazi k\'umuryango',
    exams: 'Ibizamini',
    schedule: 'Gahunda',
    // Advanced features
    artificialIntelligence: 'Ubwiyunge Bwubatswe',
    blockchain: 'Tekinoroji ya Blockchain',
    iot: 'Ibibanza bya Internet',
    biometric: 'Ibimenyetso by\'umuntu',
    augmentedReality: 'Ukuri Kwongerewe',
    predictiveAnalytics: 'Isesengura Riteganya',
    smartEnergy: 'Ingufu Zirangwa Ubwiyunge',
    quantumSecurity: 'Umutekano wa Quantum',
    // System messages
    loading: 'Birategurika...',
    error: 'Ikosa',
    success: 'Byagenze neza',
    warning: 'Iburira',
    info: 'Amakuru',
    // Support page
    supportCenter: 'Ikigo cy\'Ubufasha',
    howCanWeHelp: 'Twakugirira Iki?',
    supportDescription: 'Shakisha ibisubizo, reba amafoto yigisha, ohereza ikibazo, kandi ubone ubufasha ukeneye.',
    searchHelpArticles: 'Shakisha inyandiko z\'ubufasha, amafoto yigisha, cyangwa ibibazo bisanzwe...',
    knowledgeBase: 'Ububiko bw\'Ubumenyi',
    videoTutorials: 'Amafoto Yigisha',
    supportTickets: 'Ibizamini by\'Ubufasha',
    contactSupport: 'Twandikire kugira Ubufasha',
    submitTicket: 'Ohereza Ikibazo',
    browseArticles: 'Shakisha inyandiko z\'ubufasha',
    watchGuides: 'Reba amabwiriza akurikizwa',
    getPersonalizedHelp: 'Bonera ubufasha bwihariye',
    speakWithTeam: 'Vugana n\'ikipe yacu',
    activeUsers: 'Abakoresha Bakora',
    resolvedTickets: 'Ibibazo Byakemuwe',
    avgResponseTime: 'Igihe cy\'Isubizo',
    satisfactionRate: 'Igipimo cy\'Kunyuzwa',
    fastResponse: 'Igisubizo Cyihuse',
    available247: 'Bihari 24/7',
    articles: 'Inyandiko',
    videos: 'Amashusho',
    // Academic page
    academics: 'Amasomo',
    academicsDescription: 'Amasomo, Ibizamini n\'Ibisubizo',
    allCourses: 'Amasomo Yose',
    upcomingExams: 'Ibizamini Bizaza',
    myResults: 'Ibisubizo Byanjye',
    courseProgress: 'Iterambere ry\'Isomo',
    students: 'Abanyeshuri',
    instructor: 'Umwarimu',
    duration: 'Igihe',
    materials: 'Ibikoresho',
    viewMore: 'Reba Byinshi',
    examDate: 'Itariki y\'Ikizamini',
    examTime: 'Igihe cy\'Ikizamini',
    examRoom: 'Icyumba cy\'Ikizamini',
    score: 'Amanota',
    percentage: 'Ijanisha',
    rank: 'Umwanya',
    downloadResult: 'Kuramo Ibisubizo',
  },
  sw: {
    home: 'NYUMBANI',
    sports: 'MICHEZO',
    services: 'HUDUMA',
    trades: 'BIASHARA',
    contactUs: 'WASILIANA NASI',
    supports: 'MSAADA',
    login: 'INGIA',
    register: 'SAJILI',
    heroTitle: 'TEKNOLOJIA YA MAGARI',
    heroSubtitle: 'Kujenga Wataalamu wa Kesho Leo',
    tradesOffered: 'BIASHARA ZINAZOTOLEWA',
    softwareDevelopment: 'Utengenezaji wa Programu',
    buildingConstruction: 'Ujenzi wa Majengo',
    automobileTechnology: 'Teknolojia ya Magari',
    sod: 'SOD',
    bdc: 'BDC',
    upcomingEvents: 'MATUKIO YANAYOKUJA',
    studentParentPortal: 'LANGO LA WANAFUNZI NA WAZAZI',
    studentPortal: 'Lango la Wanafunzi',
    studentAndParent: 'Mwanafunzi & Mzazi',
    quickLinks: 'VIUNGO VYA HARAKA',
    contactInfo: 'MAELEZO YA MAWASILIANO',
    newsletter: 'JARIDA',
    email: 'Anwani ya barua pepe',
    password: 'Neno la siri',
    confirmPassword: 'Thibitisha neno la siri',
    fullName: 'Jina kamili',
    phoneNumber: 'Nambari ya simu',
    signIn: 'Ingia',
    signUp: 'Jisajili',
    enterStaffCode: 'WEKA MSIMBO WA WAFANYAKAZI',
    cancel: 'GHAIRI',
    submit: 'Wasilisha',
    searchPlaceholder: 'Tafuta kila kitu...',
    learnMore: 'Jifunze zaidi',
    viewAll: 'Tazama zote',
    getStarted: 'Anza',
    // Dashboard terms
    dashboard: 'Dashibodi',
    overview: 'Muhtasari',
    analytics: 'Uchanganuzi',
    reports: 'Ripoti',
    settings: 'Mipangilio',
    profile: 'Wasifu',
    notifications: 'Arifa',
    logout: 'Ondoka',
    // Academic terms
    courses: 'Kozi',
    grades: 'Alama',
    attendance: 'Mahudhurio',
    assignments: 'Kazi',
    exams: 'Mtihani',
    schedule: 'Ratiba',
    // Advanced features
    artificialIntelligence: 'Akili Bandia',
    blockchain: 'Blockchain',
    iot: 'Intaneti ya Vitu',
    biometric: 'Kibayometriki',
    augmentedReality: 'Uhalisia Ulioongezwa',
    predictiveAnalytics: 'Uchambuzi wa Kutabiri',
    smartEnergy: 'Nishati Mahiri',
    quantumSecurity: 'Usalama wa Quantum',
    // System messages
    loading: 'Inapakia...',
    error: 'Kosa',
    success: 'Mafanikio',
    warning: 'Onyo',
    info: 'Maelezo',
    // Support page
    supportCenter: 'Kituo cha Msaada',
    howCanWeHelp: 'Tunaweza Kukusaidia Vipi?',
    supportDescription: 'Tafuta majibu, tazama mafunzo, wasilisha tiketi, na upate msaada unaohitaji.',
    searchHelpArticles: 'Tafuta makala za msaada, mafunzo, au masuala ya kawaida...',
    knowledgeBase: 'Msingi wa Maarifa',
    videoTutorials: 'Mafunzo ya Video',
    supportTickets: 'Tiketi za Msaada',
    contactSupport: 'Wasiliana na Msaada',
    submitTicket: 'Wasilisha Tiketi',
    browseArticles: 'Vinjari makala za msaada',
    watchGuides: 'Tazama miongozo hatua kwa hatua',
    getPersonalizedHelp: 'Pata msaada wa kibinafsi',
    speakWithTeam: 'Zungumza na timu yetu',
    activeUsers: 'Watumiaji Hai',
    resolvedTickets: 'Tiketi Zilizotatuliwa',
    avgResponseTime: 'Muda wa Majibu wa Wastani',
    satisfactionRate: 'Kiwango cha Kuridhika',
    fastResponse: 'Majibu ya Haraka',
    available247: 'Inapatikana 24/7',
    articles: 'Makala',
    videos: 'Video',
    // Academic page
    academics: 'Masomo',
    academicsDescription: 'Kozi, Mitihani na Matokeo',
    allCourses: 'Kozi Zote',
    upcomingExams: 'Mitihani Inayokuja',
    myResults: 'Matokeo Yangu',
    courseProgress: 'Maendeleo ya Kozi',
    students: 'Wanafunzi',
    instructor: 'Mkufunzi',
    duration: 'Muda',
    materials: 'Vifaa',
    viewMore: 'Tazama Zaidi',
    examDate: 'Tarehe ya Mtihani',
    examTime: 'Muda wa Mtihani',
    examRoom: 'Chumba cha Mtihani',
    score: 'Alama',
    percentage: 'Asilimia',
    rank: 'Nafasi',
    downloadResult: 'Pakua Matokeo',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('rw'); // Kinyarwanda as default

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    // Return a default context instead of throwing error
    return {
      language: 'rw' as Language,
      setLanguage: () => {},
      t: (key: string) => key
    };
  }
  return context;
};
